# Generated by Django 3.2.15 on 2023-04-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0002_auto_20230406_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='regforms',
            name='ev_subhead',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='regforms',
            name='event_sub',
            field=models.TextField(default=''),
        ),
    ]
