# Generated by Django 3.2.15 on 2023-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karatte_org', '0003_auto_20230406_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='content_orid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='affilates_register',
            name='register_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
